//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Thief : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Vector2 dPad
        {
            get
            {
                return SteamVR_Actions.thief_dPad;
            }
        }
        
        public virtual SteamVR_Action_Boolean isGrabbinRight
        {
            get
            {
                return SteamVR_Actions.thief_isGrabbinRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean isGrabbinLeft
        {
            get
            {
                return SteamVR_Actions.thief_isGrabbinLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean asdasdasdas
        {
            get
            {
                return SteamVR_Actions.thief_asdasdasdas;
            }
        }
    }
}
